name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test secrets
        run: |
          echo "Токен установлен: ${{ secrets.TELEGRAM_BOT_TOKEN != '' }}"
          echo "Chat ID установлен: ${{ secrets.TELEGRAM_CHAT_ID != '' }}"
          
      - name: Send real message
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=✅+Пайплайн+в+$GITHUB_REPOSITORY+работает!"
